### ISSUE TITLE
Week 2 Activity 3

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [lmjakel/BookCollection#1]
Hi @lmjakel! Looks like you have a good start on your project structure! Can you also add your problem statement, time log, etc? These don't have to be perfect, just a first cut :) 

![Screen Shot 2021-02-01 at 12 50 48 PM](https://user-images.githubusercontent.com/13874466/106509367-29409300-6493-11eb-8338-63210550c5c3.png)

**Comment by lmjakel** [comment]
@pawaitemadisoncollege Thank you for boxing that in a screenshot for me! I couldn't remember where I was supposed to log that information yesterday when I was finishing up the exercise. Everything should be complete now but let me know if you'd like me to add anything else or be more detailed anywhere.

**Comment by pawaitemadisoncollege** [comment]
Looks good now, thank you!
