### ISSUE TITLE
Week 8 exercise

### ISSUE THREAD

**Issue by lmjakel** [lmjakel/BookCollection#7]
@pawaitemadisoncollege

I implemented the Open Library API for my project. There is A LOT of information stored in their service so I'm considering just having the user enter the isbn and then using the API to fill in the rest of the information. My thought was that using the API for the book information will help to reduce user error for spelling and such. 

One of the challenges I faced was getting the correct syntax so the search would correctly talk to the api. Another challenge was that I initially entered the incorrect script into the POJO generator so my search didn't find what it was supposed to. After you responded to my help question I was able to get it to work by correcting what was entered into the generator.

**Comment by pawaitemadisoncollege** [comment]
Glad the help on slack helped with generating the classes @lmjakel.  It's so nice to find an api that adds value to your application like this!

I'm sure these are already on your radar, but I'd be remiss if I didn't mention them:

- [ ] the base url here is a good candidate for a property read in from a property file for easy maintenance. https://github.com/lmjakel/BookCollection/blob/a23c17d2368273dfd28a6a8c39e81e6c0cd1c0d5/src/main/java/persistence/ApiDao.java#L18 
- [ ] Ideally this method will take in an isbn (as you alluded to above) https://github.com/lmjakel/BookCollection/blob/a23c17d2368273dfd28a6a8c39e81e6c0cd1c0d5/src/main/java/persistence/ApiDao.java#L14
- [ ] The unit test should test your ApiDao class/methods: https://github.com/lmjakel/BookCollection/blob/a23c17d2368273dfd28a6a8c39e81e6c0cd1c0d5/src/test/java/TestServiceClient.java#L12-L18

Throne of Glass - another item for my reading list. I can't remember if you recommended this previously, but it looks really good!
