### ISSUE TITLE
Heather's review

### ISSUE THREAD

**Issue by hmkurth** [lmjakel/BookCollection#8]
Design/Code Review 2
Project: Book Collection
Developer: LeAnne Jakel
Reviewer:  Heather Kurth
Category	Criteria	Comments
Project Overview		
	Which planned MVP functionality has been met?	**All planned mvp functionality has been met.**
	What planned MVP functionality has not been met?	
	Logging framework used, i.e., no System.out.println() or printStacktrace() statements.	**yes**
	Hibernate used for all data access.
Authentication/Authorization implemented.	**yes**
	Consumes at least one web service or public api using Java.	**Uses a library api**
	Application is database-driven using full CRUD.	**yes**
	Database includes multiple one to many relationships.	**yes**
	Deployed to AWS for public access.	**http://3.17.200.240:8080/BookCollection/**
	Implements best practices (for example, data validation)	**No data “validation” so far, but user confirmation**
	Describe the GitHub history and what it demonstrates about the project progress during the semester.	**Looks like a steady flow of progress and improvement**
	Describe how peer and instructor feedback/recommendations were incorporated into the project.	**Leanne took Tony’s suggestions and implemented equals method and generic dao**
	Other comments/notes  	**I think it was a great idea for this project, it’s not too complicated and makes good use of the practices we learned.**
JSPs		
	Evaluate the JSPs for templating, business logic, data validation, overall look and feel.	**Looks well organized, I like that you have different files for logged-in vs not,  for code efficiency I wonder if using EL and JSTL ifs might be better to use…  I did not notice any form validation, but there are confirmation messages for deletion and verification for editing.**
	Other comments/notes?	**Well written, clean code**
Java code quality	Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number). Be sure to list which code quality plugins/tools you used to assist with this analysis

•  single-purpose methods
•  well-structured project
•  descriptive naming of packages, classes, methods, variables
•  classes appropriately-sized (no monster classes)
•  CPD (copy paste detection, meaning are the same lines of code repeated?)
•  are there candidates for super/subclass relationships, abstract classes, interfaces?
•  are any values hard-coded that should be in a properties file?
•  proper exception handling
•  proper error reporting to the user
•  code documentation
•  is there code in the servlet doGet/doPoost that should be refactored into testable classes or methods?	
**I could not get any of the QA plugins to work, I got a null pointer exception in the plugin.  So I just used the out of the box intellij tools.  I have found that these these tools often pick up on things that are not even a real problem, lot’s of html or EL errors that are not really errors… and those were about all of the errors that the tools brought up, typos, EL names, SQL naming errors, css tags not matching, but nothing I could identify as an actual problem.

I do notice that you change the way the way you are naming the urlPatterns for jsps, some are /cap and some are /Cap, for consistency you may want to do it one way or another(unless you have some other reason for naming them that way)**

**You probably have to run java doc yet, not everything is perfect there, specifically SignUp.java**
Unit Tests	Evaluate the unit tests, for example:
•  tests are truly a unit test rather than a high level functional test
•  test data is appropriately cleaned up or handled
•  there is full coverage of methods that perform business logic or utility functions
•  redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After
	**Uses assertEquals to evaluate objects, looks clean, uses setup** 
	Other comments/notes?	
**I think it looks good, much cleaner than mine, that’s for sure.  It accomplishes all the things it needs to, and you have time to add more cool stuff like the images, css, and more search functions on top of a nice, working program.**

**Comment by pawaitemadisoncollege** [comment]
A couple items popped out at me as I was previewing this:

- [ ] There's a bit of repeated code creating the client builder in each of the three methods in this class. https://github.com/lmjakel/BookCollection/blob/5e28d6ac5f98f284207a085c300d50b1068f76a7/src/main/java/com/leeannjakel/persistence/ApiDao.java#L29 Might there be a way to do that work a single time?  
- [x] Externalizing the base url of the service into a property would make this easier to maintain too (you could easily change the url without making a source code change).https://github.com/lmjakel/BookCollection/blob/5e28d6ac5f98f284207a085c300d50b1068f76a7/src/main/java/com/leeannjakel/persistence/ApiDao.java#L86 -
